theme: jekyll-theme-slate
title: "MoonWalker Project: Digital Twins"

author:
    name: 

nav:
  - text: Home
    href: /
  - text: About
    href: /about
  - text: Introduction
    href: /introduction
  - text: Technologies
    href: /technologies
  - text: Skills
    href: /skills

socials:
    ElijahLinkedIn: https://www.linkedin.com/in/elijahsagaran/
    MartinLinkedIn: https://www.linkedin.com/in/martindn-ha/
    RowelLinkedIn: https://www.linkedin.com/in/rowelespejo/

images:
    Rowel: /assets/images/rowel.jpeg
    Martin: /assets/images/martin.jpg
    Elijah: /assets/images/elijah.jpg
    Logo: /assets/images/logo.png
    asset1: /assets/images/asset1.png

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one