title: "MoonWalker Project: Digital Twins"
theme: jekyll-theme-minimal

baseurl: "/MoonWalker-Collision"
url: "https://elijahsagarancsun.github.io"

author:
  name: ""

socials:
  ElijahLinkedIn: "https://www.linkedin.com/in/elijahsagaran/"
  MartinLinkedIn: "https://www.linkedin.com/in/martindn-ha/"
  RowelLinkedIn: "https://www.linkedin.com/in/rowelespejo/"

csun:
  website: "https://www.csun.edu/"
  facebook: "https://www.facebook.com/csu.northridge/"
  twitter: "https://x.com/csunorthridge"
  instagram: "https://www.instagram.com/csunorthridge/"
  linkedin: "https://www.linkedin.com/school/california-state-university-northridge/posts/?feedView=all"
  seniorDesign: "https://www.csun.edu/~xjiang/SeniorDesign/"

images:
  Rowel: "/assets/images/rowel.jpeg"
  Martin: "/assets/images/martin.jpg"
  Elijah: "/assets/images/elijah.jpg"
  Logo: "/assets/images/logo.png"
  asset1: "/assets/images/asset1.png"